<a href="https://colab.research.google.com/github/RishavRajSharma/NNDL-Lab/blob/main/NNDL_Exp_1_(numPY%2C_TF%2C_Class).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

# Activation function (ReLU)
def relu(x):
    return np.maximum(0, x)

# Softmax for output layer
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)

# Feed-forward function
def feed_forward(X, weights, biases):
    a = X
    for i in range(len(weights) - 1):
        z = np.dot(a, weights[i]) + biases[i]
        a = relu(z)

    # Output layer
    z_out = np.dot(a, weights[-1]) + biases[-1]
    output = softmax(z_out)
    return output

# Input data (batch_size=2, features=3)
X = np.array([[1.0, 0.5, -1.2],
              [0.3, 0.8, 0.2]])

# Network architecture: 3 → 4 → 2
weights = [
    np.random.randn(3, 4),  # input → hidden
    np.random.randn(4, 2)   # hidden → output
]

biases = [
    np.zeros((1, 4)),
    np.zeros((1, 2))
]

# Feed-forward pass
output = feed_forward(X, weights, biases)

print("Network Output:")
print(output)



Network Output:
[[0.90109536 0.09890464]
 [0.50208058 0.49791942]]


In [4]:
import tensorflow as tf

# Weights and biases
W1 = tf.random.normal((3, 4))
b1 = tf.zeros((4,))
W2 = tf.random.normal((4, 2))
b2 = tf.zeros((2,))

def feed_forward(X):
    z1 = tf.matmul(X, W1) + b1
    a1 = tf.nn.relu(z1)
    z2 = tf.matmul(a1, W2) + b2
    output = tf.nn.softmax(z2)
    return output

# Input
X = tf.constant([[1.0, 0.5, -1.2],
                 [0.3, 0.8, 0.2]])

print(feed_forward(X))


tf.Tensor(
[[0.20859668 0.79140335]
 [0.80082756 0.19917238]], shape=(2, 2), dtype=float32)


In [6]:
import tensorflow as tf

class FeedForwardNN:
    def __init__(self, input_size, hidden_size, output_size):
        # Initialize weights and biases
        self.W1 = tf.Variable(tf.random.normal([input_size, hidden_size]))
        self.b1 = tf.Variable(tf.zeros([hidden_size]))
        self.W2 = tf.Variable(tf.random.normal([hidden_size, output_size]))
        self.b2 = tf.Variable(tf.zeros([output_size]))

    def forward(self, X):
        # Hidden layer
        z1 = tf.matmul(X, self.W1) + self.b1
        a1 = tf.nn.relu(z1)

        # Output layer
        z2 = tf.matmul(a1, self.W2) + self.b2
        output = tf.nn.softmax(z2)

        return output
# Create input data
X = tf.constant([[1.0, 0.5, -1.2],
                 [0.3, 0.8, 0.2]])

# Create model
model = FeedForwardNN(input_size=3, hidden_size=4, output_size=2)

# Feed-forward pass
output = model.forward(X)

print("Network Output:")
print(output.numpy())


Network Output:
[[0.96520376 0.03479621]
 [0.36103734 0.6389626 ]]
